package com.flowmachine.core.model;

public enum DebugInfoReason {
  STATE_NOT_FOUND_IN_CONFIGURATION,
  TRANSITION_ATTEMPTED_FROM_FINAL_STATE,
  NO_APPLICABLE_TRANSITION_FOUND,
  EXCEPTION_DURING_TRANSITION,
  ERROR_IN_ERROR_HANDLER
}
